apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  labels:
    app: headscale
data:
  config.yaml: |
    server_url: https://{{ tpl .Values.host . }}
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 127.0.0.1:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false
    noise:
      private_key_path: {{ .Values.dataPath }}/noise_private.key
    prefixes:
      v4: {{ .Values.config.ipPrefixes.v4 | quote }}
      v6: {{ .Values.config.ipPrefixes.v6 | quote }}
      allocation: sequential
    database:
      type: sqlite
      sqlite:
        path: {{ .Values.dataPath }}/db.sqlite
    log:
      level: {{ .Values.config.logLevel }}
    policy:
      mode: file
      path: /etc/headscale/acl.json
    dns:
      magic_dns: {{ .Values.config.dns.magicDns }}
      base_domain: {{ tpl .Values.config.dns.baseDomain . | quote }}
      nameservers:
        global:
          {{- range .Values.config.dns.nameservers }}
          - {{ . | quote }}
          {{- end }}
    derp:
      server:
        enabled: {{ .Values.config.derp.serverEnabled }}
      urls:
        {{- range .Values.config.derp.urls }}
        - {{ . | quote }}
        {{- end }}
      auto_update_enabled: {{ .Values.config.derp.autoUpdate }}
      update_frequency: 24h
    ephemeral_node_inactivity_timeout: 30m
  acl.json: |
{{ tpl (.Values.config.acl | toJson) . | indent 4 }}
