apiVersion: v1
kind: Service
metadata:
  name: headscale
  labels:
    app: headscale
spec:
  type: ClusterIP
  selector:
    app: headscale
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: grpc
      port: 50443
      targetPort: grpc
