apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-issuers
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # Auto updated by parent ApplicationSet
          - list:
              elements:
                - name: skylab
          - git:
              repoURL: https://github.com/skyf0l/skylab.git
              revision: main
              files:
                - path: clusters/{{.name }}/config.json
  template:
    metadata:
      name: "{{.name}}-cert-manager-issuers"
      annotations:
        argocd.argoproj.io/sync-wave: "-7"
    spec:
      project: default
      source:
        repoURL: "{{.repo.url}}"
        targetRevision: "{{.repo.revision}}"
        path: k8s/projects/security-stack/cert-manager-issuers
        helm:
          releaseName: cert-manager-issuers
          valueFiles:
            - values.yaml
            - values/{{.name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
