apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tail-ingress
  annotations:
    # After cert-manager (cert) + traefik (IngressRoute/Middleware CRDs).
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # Auto updated by parent ApplicationSet
          - list:
              elements:
                - name: lab
          - git:
              repoURL: https://github.com/skyf0l/skylab.git
              revision: main
              files:
                - path: clusters/{{.name }}/config.json
  template:
    metadata:
      name: "{{.name}}-tail-ingress"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      source:
        repoURL: "{{.repo.url}}"
        targetRevision: "{{.repo.revision}}"
        path: k8s/projects/security-stack/tail-ingress
        helm:
          releaseName: tail-ingress
          valueFiles:
            - values.yaml
            - values/{{.name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: tail-ingress
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
