apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # Auto updated by parent ApplicationSet
          - list:
              elements:
                - name: skylab
          - git:
              repoURL: https://github.com/skyf0l/skylab.git
              revision: main
              files:
                - path: clusters/{{.name}}/config.json
  template:
    metadata:
      name: "{{.name}}-external-dns"
      labels:
        app.kubernetes.io/part-of: cluster-stack
        skylab.dev/tier: platform
    spec:
      project: platform
      source:
        repoURL: "{{.repo.url}}"
        targetRevision: "{{.repo.revision}}"
        path: k8s/projects/cluster-stack/external-dns
        helm:
          releaseName: external-dns
          valueFiles:
            - values.yaml
            - values/{{.name}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: external-dns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
        retry:
          limit: 5
