- name: Provision RKE2 cluster
  hosts: k8s_cluster
  become: true
  vars_files:
    - vars.yml
  roles:
    - role: "../../../roles/rke2/provision"

- name: "Install GitOps Stack"
  hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - role: "../../../roles/gitops/install"
