apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/skyf0l/skylab.git
        revision: main
        directories:
          # include everything under k8s/apps/*
          - path: k8s/apps/*

          # exclude specific dirs/patterns (each is its own entry)
          - path: k8s/apps/_*/** # e.g., any folder starting with "_"
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}" # app name = folder name
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/skyf0l/skylab.git
        targetRevision: main
        path: "{{path}}" # points to each folder
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}" # convention: app name = namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - PrunePropagationPolicy=foreground
          - ServerSideApply=true
          - Replace=true
