apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.vault.storeName }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kvPath | quote }}
      version: {{ .Values.vault.kvVersion | quote }}
      {{- with .Values.vault.caBundle }}
      caBundle: {{ . | quote }}
      {{- end }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.authMount | quote }}
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount | quote }}
            namespace: {{ .Values.vault.serviceAccountNamespace | quote }}
