apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflare-ddns
  name: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command:
        - 'sh'
        - '-c'
        - 'envsubst < /cloudflare-ddns-config/config.json.template > /config/config.json'
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: API_TOKEN
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: API_KEY
        - name: ACCOUNT_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: ACCOUNT_EMAIL
        - name: ZONE_ID
          valueFrom:
            secretKeyRef:
              name: cloudflare-ddns-secret
              key: ZONE_ID
        volumeMounts:
        - name: config
          mountPath: /config
        - name: cloudflare-ddns-config
          mountPath: /cloudflare-ddns-config
      containers:
      - image: cloudflare-ddns
        name: timothyjmiller/cloudflare-ddns:latest
        env:
        - name: CONFIG_PATH
          value: /etc/cloudflare-ddns/
        volumeMounts:
        - mountPath: /etc/cloudflare-ddns
          name: config-cloudflare-ddns
          readOnly: true
        resources:
          limits:
            memory: '32Mi'
            cpu: '50m'
      volumes:
      - name: cloudflare-ddns-config
        configMap:
          name: cloudflare-ddns-config
      - name: config
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-ddns-config
data:
  config.json.template: |
    {
      "cloudflare": [
        {
          "authentication": {
            "api_token": "${API_TOKEN}",
            "api_key": {
              "api_key": "${API_KEY}",
              "account_email": "${ACCOUNT_EMAIL}"
            }
          },
          "zone_id": "${ZONE_ID}",
          "subdomains": [
            {
              "name": "",
              "proxied": true
            },
            {
              "name": "pi",
              "proxied": false
            }
          ]
        }
      ],
      "a": true,
      "aaaa": true,
      "purgeUnknownRecords": false,
      "ttl": 300
    }
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-ddns-secret
# stringData:
#   API_TOKEN: xxx
#   API_KEY: xxx
#   ACCOUNT_EMAIL: xxx
#   ZONE_ID: xxx
