apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.2.7
    releaseName: argo
    namespace: argocd
    valuesFile: values.yaml
