apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kube-prometheus-stack-grafana-route
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`cluster.skyf0l.dev`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
