apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/cert-manager.yaml
  - apps/cert-manager-issuers.yaml
  - apps/external-secrets.yaml
  - apps/external-secrets-stores.yaml
  - apps/authelia.yaml
  - apps/headscale.yaml
  - apps/headscale-proxy.yaml
