{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  labels:
    app: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
  data:
    - secretKey: api_token
      remoteRef: { key: {{ .Values.externalSecret.vaultKey | quote }}, property: api_token }
{{- end }}
