apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-data
  labels:
    app: authelia
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
