apiVersion: v1
kind: Service
metadata:
  name: garmin-gateway
  labels:
    app: garmin-gateway
spec:
  type: ClusterIP
  selector:
    app: garmin-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
