global:
  domain: argocd.skyf0l.dev

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    extraTls:
      - hosts:
          - argocd.skyf0l.dev

configs:
  params:
    server.insecure: true
