apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/skyf0l/skylab.git"
    path: cloudflare-ddns
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
