apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/skyf0l/skylab.git'
    path: tor
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
