apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://traefik.github.io/charts'
    targetRevision: 34.3.0
    chart: traefik
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/skyf0l/skylab.git'
    ref: values
    path: traefik
    targetRevision: HEAD
  - repoURL: 'https://github.com/skyf0l/skylab.git'
    path: traefik
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
