apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart from upstream
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.2.7
      helm:
        releaseName: argo
        valueFiles:
          - $values/k8s/src/argocd/values.yaml
    # Values from this repo
    - repoURL: https://github.com/skyf0l/skylab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
