apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-stack/applications.yaml
  - security-stack/applications.yaml
  - gitops-stack/applications.yaml
  - mcp-stack/applications.yaml
  - mail-stack/applications.yaml
  - finops/applications.yaml
  - core/applications.yaml
  - observability/applications.yaml
