apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-stack/applications.yaml
  - gitops-stack/applications.yaml
  - finops/applications.yaml
  - core/applications.yaml
  - observability/applications.yaml
  - network/applications.yaml
  - identity/applications.yaml
  - security/applications.yaml
  - workloads/applications.yaml
